function hasDB(e){return !!(e&&e.db)}
async function initDB(e){
  if(!hasDB(e))return;
  try{await e.db.exec("CREATE TABLE IF NOT EXISTS users(id INTEGER PRIMARY KEY AUTOINCREMENT,username TEXT UNIQUE NOT NULL,password_hash TEXT NOT NULL,role TEXT DEFAULT 'user',created_at TEXT DEFAULT (datetime('now')));CREATE TABLE IF NOT EXISTS categories(id INTEGER PRIMARY KEY AUTOINCREMENT,name TEXT UNIQUE NOT NULL,description TEXT DEFAULT '');CREATE TABLE IF NOT EXISTS threads(id INTEGER PRIMARY KEY AUTOINCREMENT,title TEXT NOT NULL,content TEXT NOT NULL,user_id INTEGER NOT NULL,category_id INTEGER DEFAULT 1,pinned INTEGER DEFAULT 0,views INTEGER DEFAULT 0,created_at TEXT DEFAULT (datetime('now')),updated_at TEXT DEFAULT (datetime('now')));CREATE TABLE IF NOT EXISTS posts(id INTEGER PRIMARY KEY AUTOINCREMENT,content TEXT NOT NULL,user_id INTEGER NOT NULL,thread_id INTEGER NOT NULL,created_at TEXT DEFAULT (datetime('now')));CREATE TABLE IF NOT EXISTS sessions(id INTEGER PRIMARY KEY AUTOINCREMENT,user_id INTEGER NOT NULL,token TEXT UNIQUE NOT NULL,expires_at TEXT NOT NULL);INSERT OR IGNORE INTO categories(id,name,description)VALUES(1,'默认版块','默认讨论版块')")}
  catch(e){console.error(e)}
}
async function hashPw(p){
  var s=crypto.getRandomValues(new Uint8Array(16)),k=await crypto.subtle.importKey('raw',new TextEncoder().encode(p),'PBKDF2',false,['deriveBits']),
  b=await crypto.subtle.deriveBits({name:'PBKDF2',salt:s,iterations:1e5,hash:'SHA-256'},k,256),
  h=btoa(String.fromCharCode(...new Uint8Array(b)));
  return btoa(String.fromCharCode(...s))+':'+h
}
async function verPw(p,st){
  var a=st.split(':'),s=new Uint8Array([...atob(a[0])].map(function(c){return c.charCodeAt(0)})),
  k=await crypto.subtle.importKey('raw',new TextEncoder().encode(p),'PBKDF2',false,['deriveBits']),
  b=await crypto.subtle.deriveBits({name:'PBKDF2',salt:s,iterations:1e5,hash:'SHA-256'},k,256);
  return btoa(String.fromCharCode(...new Uint8Array(b)))===a[1]
}
function genT(){return Array.from(crypto.getRandomValues(new Uint8Array(32)),function(b){return b.toString(16).padStart(2,'0')}).join('')}
function sanit(s){return typeof s!='string'?'':s.replace(/&/g,'&amp;').replace(/</g,'&lt;').replace(/>/g,'&gt;').replace(/"/g,'&quot;')}
function parC(c){var o={};if(c)c.split(';').forEach(function(x){var p=x.trim().split('=');if(p.length>=2)o[p[0]]=p.slice(1).join('=')});return o}
function setC(t){return 'nw_forum_token='+t+'; HttpOnly; Secure; Path=/; SameSite=Lax; Expires='+new Date(Date.now()+7*864e5).toUTCString()}
function clrC(){return 'nw_forum_token=; HttpOnly; Secure; Path=/; SameSite=Lax; Expires=Thu, 01 Jan 1970 00:00:00 GMT'}
function json(d,s){return new Response(JSON.stringify(d),{status:s||200,headers:{'Content-Type':'application/json;charset=utf-8'}})}
async function getU(e,r){
  if(!hasDB(e))return null;
  var t=parC(r.headers.get('Cookie')||'')['nw_forum_token'];
  if(!t)return null;
  try{return await e.db.prepare("SELECT u.id,u.username,u.role FROM sessions s JOIN users u ON s.user_id=u.id WHERE s.token=? AND s.expires_at>datetime('now')").bind(t).first()||null}
  catch(er){return null}
}
async function apiReg(e,b){
  if(!hasDB(e))return json({error:'数据库未配置'},503);
  var u=b.username,p=b.password;
  if(!u||!p||u.length<2||u.length>20||p.length<6)return json({error:'用户名2-20字符，密码至少6字符'},400);
  if(!/^[a-zA-Z0-9_\u4e00-\u9fa5]+$/.test(u))return json({error:'用户名只允许字母、数字、下划线和中文'},400);
  try{if(await e.db.prepare('SELECT id FROM users WHERE username=?').bind(u).first())return json({error:'用户名已存在'},409);var ph=await hashPw(p),c=await e.db.prepare('SELECT COUNT(*)as c FROM users').first(),r=(c&&c.c===0)?'admin':'user';await e.db.prepare('INSERT INTO users(username,password_hash,role)VALUES(?,?,?)').bind(u,ph,r).run();return json({message:'注册成功',role:r})}
  catch(er){return json({error:'注册失败'},500)}
}
async function apiLog(e,b){
  if(!hasDB(e))return json({error:'数据库未配置'},503);
  var u=b.username,p=b.password;
  if(!u||!p)return json({error:'请填写用户名和密码'},400);
  try{var us=await e.db.prepare('SELECT * FROM users WHERE username=?').bind(u).first();if(!us||!(await verPw(p,us.password_hash)))return json({error:'用户名或密码错误'},401);var t=genT(),h=new Headers({'Content-Type':'application/json'});h.append('Set-Cookie',setC(t));await e.db.prepare("INSERT INTO sessions(user_id,token,expires_at)VALUES(?,?,datetime('now','+7 days'))").bind(us.id,t).run();return new Response(JSON.stringify({message:'登录成功',id:us.id,username:us.username,role:us.role}),{status:200,headers:h})}
  catch(er){return json({error:'登录失败'},500)}
}
async function apiOut(e,r){
  if(!hasDB(e)){var h=new Headers();h.append('Set-Cookie',clrC());h.append('Content-Type','application/json');return new Response(JSON.stringify({message:'已登出'}),{headers:h})}
  var t=parC(r.headers.get('Cookie')||'')['nw_forum_token'];if(t)try{await e.db.prepare('DELETE FROM sessions WHERE token=?').bind(t).run()}catch(er){}
  var h=new Headers({'Content-Type':'application/json'});h.append('Set-Cookie',clrC());return new Response(JSON.stringify({message:'已登出'}),{headers:h})
}
async function apiMe(e,r){var u=await getU(e,r);if(!u)return json({error:'未登录'},401);return json({user:{id:u.id,username:u.username,role:u.role}})}
async function apiThr(e,r){
  if(!hasDB(e))return json({threads:[],total:0,page:1,totalPages:0});
  var u=new URL(r.url),p=Math.max(1,parseInt(u.searchParams.get('page'))||1),l=20,o=(p-1)*l;
  try{var cnt=await e.db.prepare('SELECT COUNT(*)as total FROM threads').first(),t=cnt?cnt.total:0,rows=await e.db.prepare('SELECT t.id,t.title,t.user_id,t.pinned,t.views,t.created_at,t.updated_at,u.username FROM threads t JOIN users u ON t.user_id=u.id ORDER BY t.pinned DESC,t.updated_at DESC LIMIT ? OFFSET ?').bind(l,o).all();return json({threads:rows.results||[],total:t,page:p,totalPages:Math.ceil(t/l)})}
  catch(er){return json({threads:[],total:0,page:1,totalPages:0})}
}
async function apiThrD(e,id){
  if(!hasDB(e))return json({error:'数据库未配置'},503);
  try{var t=await e.db.prepare('SELECT t.*,u.username FROM threads t JOIN users u ON t.user_id=u.id WHERE t.id=?').bind(id).first();if(!t)return json({error:'帖子不存在'},404);await e.db.prepare('UPDATE threads SET views=views+1 WHERE id=?').bind(id).run();var ps=await e.db.prepare('SELECT p.*,u.username,u.role FROM posts p JOIN users u ON p.user_id=u.id WHERE p.thread_id=? ORDER BY p.created_at ASC').bind(id).all();return json({thread:t,posts:ps.results||[]})}
  catch(er){return json({error:'查询失败'},500)}
}
async function apiCThr(e,r,b){var u=await getU(e,r);if(!u)return json({error:'请先登录'},401);if(!hasDB(e))return json({error:'数据库未配置'},503);if(!b.title||!b.content)return json({error:'标题和内容不能为空'},400);if(b.title.length>100)return json({error:'标题不能超过100字符'},400);try{var re=await e.db.prepare('INSERT INTO threads(title,content,user_id)VALUES(?,?,?)').bind(sanit(b.title),sanit(b.content),u.id).run();return json({message:'发帖成功',id:re.meta.last_row_id},201)}catch(er){return json({error:'发帖失败'},500)}}
async function apiCPo(e,r,b){var u=await getU(e,r);if(!u)return json({error:'请先登录'},401);if(!hasDB(e))return json({error:'数据库未配置'},503);if(!b.content)return json({error:'内容不能为空'},400);try{if(!await e.db.prepare('SELECT id FROM threads WHERE id=?').bind(b.thread_id).first())return json({error:'帖子不存在'},404);await e.db.prepare('INSERT INTO posts(content,user_id,thread_id)VALUES(?,?,?)').bind(sanit(b.content),u.id,b.thread_id).run();await e.db.prepare("UPDATE threads SET updated_at=datetime('now') WHERE id=?").bind(b.thread_id).run();return json({message:'回复成功'},201)}catch(er){return json({error:'回复失败'},500)}}
async function apiDTh(e,r,id){var u=await getU(e,r);if(!u)return json({error:'未登录'},401);if(!hasDB(e))return json({error:'数据库未配置'},503);try{var t=await e.db.prepare('SELECT user_id FROM threads WHERE id=?').bind(id).first();if(!t)return json({error:'帖子不存在'},404);if(u.role!=='admin'&&t.user_id!==u.id)return json({error:'无权操作'},403);await e.db.prepare('DELETE FROM posts WHERE thread_id=?').bind(id).run();await e.db.prepare('DELETE FROM threads WHERE id=?').bind(id).run();return json({message:'删除成功'})}catch(er){return json({error:'删除失败'},500)}}
async function apiDPo(e,r,id){var u=await getU(e,r);if(!u)return json({error:'未登录'},401);if(!hasDB(e))return json({error:'数据库未配置'},503);try{var p=await e.db.prepare('SELECT user_id FROM posts WHERE id=?').bind(id).first();if(!p)return json({error:'回复不存在'},404);if(u.role!=='admin'&&p.user_id!==u.id)return json({error:'无权操作'},403);await e.db.prepare('DELETE FROM posts WHERE id=?').bind(id).run();return json({message:'删除成功'})}catch(er){return json({error:'删除失败'},500)}}
async function apiAS(e,r){var u=await getU(e,r);if(!u||u.role!=='admin')return json({error:'无权访问'},403);if(!hasDB(e))return json({error:'数据库未配置'},503);try{var uc=await e.db.prepare('SELECT COUNT(*)as c FROM users').first(),tc=await e.db.prepare('SELECT COUNT(*)as c FROM threads').first(),pc=await e.db.prepare('SELECT COUNT(*)as c FROM posts').first(),ru=await e.db.prepare('SELECT id,username,role,created_at FROM users ORDER BY created_at DESC LIMIT 5').all();return json({users:uc.c,threads:tc.c,posts:pc.c,recentUsers:ru.results||[]})}catch(er){return json({error:'查询失败'},500)}}
async function apiAU(e,r){var u=await getU(e,r);if(!u||u.role!=='admin')return json({error:'无权访问'},403);if(!hasDB(e))return json({error:'数据库未配置'},503);try{var rows=await e.db.prepare('SELECT id,username,role,created_at FROM users ORDER BY id').all();return json(rows.results||[])}catch(er){return json({error:'查询失败'},500)}}
async function apiASR(e,r,b){var u=await getU(e,r);if(!u||u.role!=='admin')return json({error:'无权访问'},403);if(!hasDB(e))return json({error:'数据库未配置'},503);if(!['user','admin'].includes(b.role))return json({error:'无效角色'},400);try{await e.db.prepare('UPDATE users SET role=? WHERE id=?').bind(b.role,b.user_id).run();return json({message:'角色已更新'})}catch(er){return json({error:'更新失败'},500)}}
async function apiAD(e,r,id){var u=await getU(e,r);if(!u||u.role!=='admin')return json({error:'无权访问'},403);if(parseInt(id)===u.id)return json({error:'不能删除自己'},400);if(!hasDB(e))return json({error:'数据库未配置'},503);try{await e.db.prepare('DELETE FROM sessions WHERE user_id=?').bind(id).run();await e.db.prepare('DELETE FROM posts WHERE user_id=?').bind(id).run();await e.db.prepare('DELETE FROM threads WHERE user_id=?').bind(id).run();await e.db.prepare('DELETE FROM users WHERE id=?').bind(id).run();return json({message:'用户已删除'})}catch(er){return json({error:'删除失败'},500)}}

// ─── 前端渲染 ───
function page(u){
  var uj=JSON.stringify(u?{id:u.id,username:u.username,role:u.role}:null);
  var c='*,*::before,*::after{box-sizing:border-box;margin:0;padding:0}:root{--bg:#f5f7fa;--s:#fff;--s2:#f0f2f5;--t:#1a1a2e;--t2:#6b7280;--p:#6366f1;--ph:#4f46e5;--pl:#eef2ff;--d:#ef4444;--dh:#dc2626;--g:#22c55e;--b:#e5e7eb;--sh:0 1px 3px rgba(0,0,0,.08);--shl:0 8px 32px rgba(0,0,0,.1);--r:12px;--rs:8px;--tr:.3s cubic-bezier(.4,0,.2,1)}';
  c+='body{font-family:-apple-system,BlinkMacSystemFont,"Segoe UI",Roboto,sans-serif;background:var(--bg);color:var(--t);line-height:1.6}a{color:var(--p);text-decoration:none;transition:color var(--tr)}a:hover{color:var(--ph)}';
  c+='.navbar{display:flex;align-items:center;justify-content:space-between;height:60px;padding:0 24px;background:#fff;border-bottom:1px solid var(--b);position:sticky;top:0;z-index:100;box-shadow:var(--sh)}';
  c+='.navbar .logo{font-size:1.2rem;font-weight:700;background:linear-gradient(135deg,var(--p),#a855f7);-webkit-background-clip:text;-webkit-text-fill-color:transparent;background-clip:text}';
  c+='.nav-r{display:flex;align-items:center;gap:12px}.nav-r a,.nav-r button{padding:8px 16px;border-radius:var(--rs);transition:all var(--tr);font-size:.875rem;cursor:pointer;border:none;background:none;color:var(--t2);font-family:inherit}.nav-r a:hover,.nav-r button:hover{background:var(--s2);color:var(--t)}';
  c+='.btn{display:inline-flex;align-items:center;gap:6px;padding:10px 20px;border:none;border-radius:var(--rs);font-size:.875rem;font-weight:500;cursor:pointer;transition:all var(--tr);font-family:inherit;background:var(--s2);color:var(--t)}';
  c+='.btn:hover{transform:translateY(-1px);box-shadow:var(--shl)}.btn-p{background:var(--p);color:#fff}.btn-p:hover{background:var(--ph)}';
  c+='.btn-d{background:var(--d);color:#fff}.btn-d:hover{background:var(--dh)}.btn-sm{padding:6px 12px;font-size:.8rem}';
  c+='.container{max-width:960px;margin:0 auto;padding:24px 16px}.card{background:var(--s);border-radius:var(--r);padding:20px;box-shadow:var(--sh);border:1px solid var(--b);margin-bottom:12px;transition:all var(--tr)}';
  c+='.card:hover{box-shadow:var(--shl)}.form-group{margin-bottom:16px}.form-group label{display:block;font-size:.875rem;font-weight:500;margin-bottom:6px;color:var(--t2)}';
  c+='.form-input,.form-textarea{width:100%;padding:10px 14px;border:2px solid var(--b);border-radius:var(--rs);font-size:.9rem;transition:all var(--tr);background:var(--s);color:var(--t);font-family:inherit;outline:none;box-sizing:border-box}';
  c+='.form-input:focus,.form-textarea:focus{border-color:var(--p);box-shadow:0 0 0 3px var(--pl)}.form-textarea{min-height:120px;resize:vertical}';
  c+='.auth-wrap{max-width:420px;margin:60px auto}.auth-tabs{display:flex;margin-bottom:24px;background:var(--s2);border-radius:var(--rs);overflow:hidden}';
  c+='.auth-tabs button{flex:1;padding:12px;border:none;font-size:.9rem;font-weight:500;cursor:pointer;color:var(--t2);font-family:inherit;transition:all var(--tr)}';
  c+='.auth-tabs button.active{background:var(--p);color:#fff}.auth-form{display:none;animation:.3s fade}.auth-form.active{display:block}';
  c+='@keyframes fade{from{opacity:0;transform:translateY(12px)}to{opacity:1;transform:translateY(0)}}';
  c+='.ld{text-align:center;padding:40px;color:var(--t2)}';
  c+='.spinner{width:32px;height:32px;border:3px solid var(--b);border-top-color:var(--p);border-radius:50%;animation:spin .8s linear infinite;margin:0 auto 12px}@keyframes spin{to{transform:rotate(360deg)}}';
  c+='.toast-wrap{position:fixed;top:80px;right:20px;z-index:300;display:flex;flex-direction:column;gap:8px}';
  c+='.toast{padding:12px 20px;border-radius:var(--rs);background:var(--s);box-shadow:var(--shl);font-size:.875rem;border-left:4px solid var(--p);max-width:320px;animation:sl .3s ease}';
  c+='.toast.e{border-left-color:var(--d)}.toast.ok{border-left-color:var(--g)}@keyframes sl{from{opacity:0;transform:translateX(40px)}to{opacity:1;transform:translateX(0)}}';
  c+='.empty{text-align:center;padding:60px 20px;color:var(--t2)}';
  c+='.thread-item{display:flex;gap:16px;padding:16px 0;border-bottom:1px solid var(--b);cursor:pointer;transition:all var(--tr)}.thread-item:last-child{border-bottom:none}.thread-item:hover{padding-left:8px}';
  c+='.thread-title{font-size:1.05rem;font-weight:600;color:var(--t);margin-bottom:4px}.thread-meta{font-size:.8rem;color:var(--t2);display:flex;gap:16px;flex-wrap:wrap}';
  c+='.thread-stats{text-align:right;flex-shrink:0;font-size:.85rem;color:var(--t2)}';
  c+='.thread-header{margin-bottom:20px;padding-bottom:16px;border-bottom:1px solid var(--b)}.thread-header h1{font-size:1.5rem;margin-bottom:8px}';
  c+='.thread-content{white-space:pre-wrap;word-break:break-word;font-size:.95rem;line-height:1.8}';
  c+='.post-item{padding:16px;border-left:3px solid var(--p);background:var(--s2);border-radius:0 var(--rs) var(--rs) 0;margin-bottom:12px}';
  c+='.post-header{display:flex;justify-content:space-between;margin-bottom:8px;font-size:.85rem}.post-author{font-weight:600;display:flex;align-items:center;gap:8px}';
  c+='.post-content{white-space:pre-wrap;word-break:break-word;font-size:.9rem}';
  c+='.pagination{display:flex;justify-content:center;gap:8px;margin-top:24px}.pagination button{padding:8px 14px;border:1px solid var(--b);background:var(--s);border-radius:var(--rs);cursor:pointer;font-family:inherit;font-size:.85rem}';
  c+='.pagination button:hover{background:var(--s2)}.pagination button.active{background:var(--p);color:#fff;border-color:var(--p)}.pagination button:disabled{opacity:.4;cursor:not-allowed}';
  c+='.admin-bar{display:flex;gap:8px;margin-bottom:24px;flex-wrap:wrap}.admin-bar button{padding:10px 20px;border:2px solid var(--b);background:var(--s);border-radius:var(--rs);cursor:pointer;font-size:.85rem;font-weight:500;color:var(--t2);font-family:inherit}';
  c+='.admin-bar button:hover{border-color:var(--p)}.admin-bar button.active{background:var(--p);color:#fff;border-color:var(--p)}';
  c+='.admin-stats{display:grid;grid-template-columns:repeat(auto-fit,minmax(140px,1fr));gap:12px;margin-bottom:24px}';
  c+='.admin-stats .card{text-align:center;padding:20px}.stat-num{font-size:2rem;font-weight:700;color:var(--p)}.stat-label{font-size:.85rem;color:var(--t2);margin-top:4px}';
  c+='.tbl{width:100%;border-collapse:collapse;font-size:.85rem}.tbl th{text-align:left;padding:12px 8px;border-bottom:2px solid var(--b);color:var(--t2);font-weight:600}.tbl td{padding:10px 8px;border-bottom:1px solid var(--b)}.tbl tr:hover td{background:var(--s2)}';
  c+='.badge{background:var(--d);color:#fff;padding:2px 8px;border-radius:99px;font-size:.7rem;font-weight:600;margin-left:6px}';
  c+='.nav-user{display:flex;align-items:center;gap:8px;font-size:.875rem}.nav-avatar{width:32px;height:32px;border-radius:50%;background:linear-gradient(135deg,var(--p),#a855f7);color:#fff;display:flex;align-items:center;justify-content:center;font-weight:600;font-size:.8rem}';
  c+='@media(max-width:640px){.navbar{padding:0 12px}.container{padding:16px 12px}.auth-wrap{margin:30px auto}.thread-stats{display:none}}';
  var h='<!DOCTYPE html><html lang="zh-CN"><head><meta charset="UTF-8"><meta name="viewport" content="width=device-width,initial-scale=1.0"><title>NW Forum</title><style>'+c+'</style></head><body>';
  h+='<nav class="navbar"><a href="/" class="logo">NW Forum</a><div class="nav-r">';
  h+='<span class="nav-user" id="navU" style="display:none"><span class="nav-avatar" id="navAV">U</span><span id="navUN"></span><span class="badge" id="navBADGE" style="display:none">管理员</span></span>';
  h+='<a href="/profile" id="nProL" style="display:none">个人</a><a href="/">首页</a><a href="/new" id="nNewL" style="display:none">发帖</a><a href="/admin" id="nAdmL" style="display:none">管理</a><a href="/login" id="nLogL">登录</a>';
  h+='<button id="nOutB" style="display:none" class="btn btn-sm">登出</button></div></nav>';
  h+='<div class="toast-wrap" id="toasts"></div><main class="container" id="app"><div class="ld"><div class="spinner"></div><p>加载中...</p></div></main>';
  h+='<script>var CU='+uj+',cp=1;';
  h+='function esc(s){var d=document.createElement("div");d.textContent=s||"";return d.innerHTML}';
  h+='function toast(msg,ty){var c=document.getElementById("toasts"),d=document.createElement("div");d.className="toast "+(ty==="error"?"e":"ok");d.textContent=msg;c.appendChild(d);setTimeout(function(){d.remove()},3000)}';
  h+='function api(m,p,b){var o={method:m,headers:{}};if(b){o.headers["Content-Type"]="application/json";o.body=JSON.stringify(b)}return fetch("/api"+p,o).then(function(r){return r.json().then(function(d){if(!r.ok&&d.error)throw new Error(d.error);return d})})}';
  h+='function nv(e,p){e&&e.preventDefault();history.pushState(null,"",p);rt()}';
  h+='window.addEventListener("popstate",rt);';
  h+='function upd(){var l=document.getElementById("nLogL"),o=document.getElementById("nOutB"),u=document.getElementById("navU"),a=document.getElementById("navAV"),n=document.getElementById("navUN"),b=document.getElementById("navBADGE"),nn=document.getElementById("nNewL"),na=document.getElementById("nAdmL"),np=document.getElementById("nProL");if(CU){l.style.display="none";o.style.display="";u.style.display="";a.textContent=CU.username.charAt(0);n.textContent=CU.username;b.style.display=CU.role==="admin"?"":"none";nn.style.display="";na.style.display=CU.role==="admin"?"":"none";np.style.display=""}else{l.style.display="";o.style.display="none";u.style.display="none";nn.style.display="none";na.style.display="none";np.style.display="none"}}';
  h+='function ago(d){var dt=new Date(d+"Z"),s=Math.floor((new Date()-dt)/1000);if(s<60)return"刚刚";var m=Math.floor(s/60);if(m<60)return m+"分钟前";var h=Math.floor(m/60);if(h<24)return h+"小时前";var dy=Math.floor(h/24);if(dy<30)return dy+"天前";return(d||"").split(" ")[0]}';
  h+='document.getElementById("nLogL").onclick=function(e){nv(e,"/login")};document.getElementById("nOutB").onclick=function(){api("POST","/auth/logout").then(function(){CU=null;upd();nv(null,"/")})};';
  h+='Array.from(document.querySelectorAll(".navbar a")).forEach(function(a){if(a.getAttribute("href")!=="/")a.onclick=function(e){nv(e,a.getAttribute("href"))}});';
  h+='function rt(){var p=window.location.pathname;if(p==="/login"){pgL()}else if(p==="/new"){pgN()}else if(p==="/admin"){pgA()}else if(p==="/profile"){pgP()}else if(p.indexOf("/thread/")===0){pgT(p.split("/")[2])}else{pgH()}}';
  h+='function pgH(){var e=document.getElementById("app");e.innerHTML=("<div class=\\"pg\\"><div style=\\"display:flex;justify-content:space-between;align-items:center;margin-bottom:20px\\"><h2 style=\\"margin:0\\">全部帖子</h2>"+(CU?"<button class=\\"btn btn-p\\" id=\\"newTB\\">+发新帖</button>":"")+"</div><div class=\\"ld\\"><div class=\\"spinner\\"></div><p>加载中...</p></div></div>");if(CU)document.getElementById("newTB").onclick=function(e){nv(e,"/new")};api("GET","/threads?page="+cp).then(function(d){var h="<div style=\\"display:flex;justify-content:space-between;align-items:center;margin-bottom:20px\\"><h2 style=\\"margin:0\\">全部帖子</h2>"+(CU?"<button class=\\"btn btn-p\\" id=\\"newTB2\\">+发新帖</button>":"")+"</div>";if(!d.threads||!d.threads.length){h+="<div class=\\"card empty\\"><p>还没有帖子</p></div>"}else{d.threads.forEach(function(t){h+="<div class=\\"card thread-item\\" data-id=\\""+t.id+"\\"><div class=\\"thread-info\\"><div class=\\"thread-title\\">"+esc(t.title)+"</div><div class=\\"thread-meta\\"><span>"+esc(t.username)+"</span><span>"+ago(t.created_at)+"</span></div></div><div class=\\"thread-stats\\"><div>0</div><div>"+t.views+"</div></div></div>"})}if(d.totalPages>1){h+="<div class=\\"pagination\\"><button "+(cp<=1?"disabled":"")+" onclick=\\"cp="+(cp-1)+";pgH()\\">上一页</button>";for(var i=1;i<=d.totalPages;i++)h+="<button onclick=\\"cp="+i+";pgH()\\" "+(i===cp?"class=\\"active\\"":"")+">"+i+"</button>";h+="<button "+(cp>=d.totalPages?"disabled":"")+" onclick=\\"cp="+(cp+1)+";pgH()\\">下一页</button></div>"}e.innerHTML="<div class=\\"pg\\">"+h+"</div>";if(CU)document.getElementById("newTB2").onclick=function(e){nv(e,"/new")};Array.from(document.querySelectorAll("[data-id]")).forEach(function(el){el.onclick=function(){nv(null,"/thread/"+el.getAttribute("data-id"))}})}).catch(function(er){console.log(er);document.getElementById("app").innerHTML="<div class=\\"pg\\"><div class=\\"card empty\\"><p>加载失败:"+er.message+"</p></div></div>"})}';
  h+='function pgT(id){var e=document.getElementById("app");e.innerHTML="<div class=\\"pg\\"><div class=\\"ld\\"><div class=\\"spinner\\"></div><p>加载中...</p></div></div>";api("GET","/threads/"+id).then(function(d){var t=d.thread,ps=d.posts||[],h;h="<a href=\\"/\\" style=\\"margin-bottom:12px;display:inline-block\\"></a><div class=\\"card\\"><div class=\\"thread-header\\"><h1>"+esc(t.title)+"</h1><div class=\\"thread-meta\\"><span>"+esc(t.username)+"</span><span>"+t.created_at+"</span><span>"+t.views+"次浏览</span></div></div><div class=\\"thread-content\\">"+esc(t.content)+"</div>"+(CU&&(CU.role==="admin"||CU.id===t.user_id)?"<div style=\\"margin-top:12px\\"><button class=\\"btn btn-d btn-sm\\" id=\\"delThrB\\">删除</button></div>":"")+"</div><h3 style=\\"margin:20px 0 12px\\">回复("+ps.length+")</h3>";if(!ps.length)h+="<p style=\\"color:var(--t2);margin-bottom:16px\\">暂无回复</p>";ps.forEach(function(p){h+="<div class=\\"post-item\\"><div class=\\"post-header\\"><span class=\\"post-author\\">"+esc(p.username)+(p.role==="admin"?" <span class=\\"badge\\">管理员</span>":"")+"</span><span style=\\"font-size:.8rem;color:var(--t2)\\">"+ago(p.created_at)+"</span></div><div class=\\"post-content\\">"+esc(p.content)+"</div>"+(CU&&(CU.role==="admin"||CU.id===p.user_id)?"<div style=\\"margin-top:8px\\"><button class=\\"btn btn-d btn-sm\\" data-dp=\\""+p.id+"\\">删除</button></div>":"")+"</div>"});if(CU)h+="<div class=\\"card\\"><h4 style=\\"margin-bottom:12px\\">发表回复</h4><textarea class=\\"form-textarea\\" id=\\"rpC\\" placeholder=\\"写下你的回复...\\" style=\\"margin-bottom:12px\\"></textarea><button class=\\"btn btn-p\\" id=\\"rpB\\">发表回复</button></div>";e.innerHTML="<div class=\\"pg\\">"+h+"</div>";if(document.getElementById("delThrB"))document.getElementById("delThrB").onclick=function(){if(!confirm("确定删除？"))return;api("DELETE","/threads/"+id).then(function(){toast("已删除");nv(null,"/")})};Array.from(document.querySelectorAll("[data-dp]")).forEach(function(el){el.onclick=function(){var pi=el.getAttribute("data-dp");if(!confirm("确定删除？"))return;api("DELETE","/posts/"+pi).then(function(){toast("已删除");pgT(id)})}});if(document.getElementById("rpB"))document.getElementById("rpB").onclick=function(){var c=document.getElementById("rpC").value;if(!c.trim())return toast("请输入内容","error");api("POST","/posts",{content:c,thread_id:parseInt(id)}).then(function(){toast("回复成功");pgT(id)})}}).catch(function(){e.innerHTML="<div class=\\"pg\\"><p>加载失败</p></div>"})}';
  h+='function pgN(){if(!CU){toast("请先登录","error");nv(null,"/login");return}var e=document.getElementById("app");e.innerHTML="<div class=\\"pg\\"><h2 style=\\"margin-bottom:20px\\">发布新帖</h2><div class=\\"card\\"><div class=\\"form-group\\"><label>标题</label><input class=\\"form-input\\" id=\\"thrT\\" placeholder=\\"帖子标题\\" maxlength=\\"100\\"></div><div class=\\"form-group\\"><label>内容</label><textarea class=\\"form-textarea\\" id=\\"thrC\\" placeholder=\\"写下内容...\\" style=\\"min-height:180px\\"></textarea></div><button class=\\"btn btn-p\\" id=\\"thrB\\">发布帖子</button></div></div>";document.getElementById("thrB").onclick=function(){var ti=document.getElementById("thrT").value,co=document.getElementById("thrC").value;if(!ti.trim())return toast("请输入标题","error");if(!co.trim())return toast("请输入内容","error");api("POST","/threads",{title:ti,content:co}).then(function(){toast("发帖成功");nv(null,"/")})}}';
h+='function pgP(){if(!CU){toast("请先登录","error");nv(null,"/login");return}var e=document.getElementById("app");e.innerHTML="<div class=\\"pg\\"><h2>个人设置</h2><div class=\\"card\\"><div class=\\"form-group\\"><label>用户名</label><input class=\\"form-input\\" value=\\""+esc(CU.username)+"\\" disabled></div><div class=\\"form-group\\"><label>角色</label><input class=\\"form-input\\" value=\\""+(CU.role==="admin"?"管理员":"普通用户")+"\\" disabled></div></div></div>"}';
  h+='function pgL(){var e=document.getElementById("app");e.innerHTML="<div class=\\"pg auth-wrap\\"><h2 style=\\"text-align:center;margin-bottom:8px\\">欢迎回来</h2><p style=\\"text-align:center;color:var(--t2);margin-bottom:24px\\">登录或注册</p><div class=\\"auth-tabs\\"><button id=\\"tabL\\" class=\\"active\\">登录</button><button id=\\"tabR\\">注册</button></div><div id=\\"formL\\" class=\\"auth-form active\\"><div class=\\"form-group\\"><label>用户名</label><input class=\\"form-input\\" id=\\"lgU\\" placeholder=\\"输入用户名\\"></div><div class=\\"form-group\\"><label>密码</label><input class=\\"form-input\\" type=\\"password\\" id=\\"lgP\\" placeholder=\\"输入密码\\"></div><button class=\\"btn btn-p\\" style=\\"width:100%;justify-content:center\\" id=\\"lgB\\">登录</button></div><div id=\\"formR\\" class=\\"auth-form\\"><div class=\\"form-group\\"><label>用户名</label><input class=\\"form-input\\" id=\\"rgU\\" placeholder=\\"2-20个字符\\"></div><div class=\\"form-group\\"><label>密码</label><input class=\\"form-input\\" type=\\"password\\" id=\\"rgP\\" placeholder=\\"至少6个字符\\"></div><button class=\\"btn btn-p\\" style=\\"width:100%;justify-content:center\\" id=\\"rgB\\">注册</button></div></div>";document.getElementById("tabL").onclick=function(){document.getElementById("formR").classList.remove("active");document.getElementById("formL").classList.add("active");document.getElementById("tabR").classList.remove("active");document.getElementById("tabL").classList.add("active")};document.getElementById("tabR").onclick=function(){document.getElementById("formL").classList.remove("active");document.getElementById("formR").classList.add("active");document.getElementById("tabL").classList.remove("active");document.getElementById("tabR").classList.add("active")};document.getElementById("lgB").onclick=function(){var u=document.getElementById("lgU").value,p=document.getElementById("lgP").value;api("POST","/auth/login",{username:u,password:p}).then(function(d){CU={id:d.id,username:d.username,role:d.role};upd();toast("登录成功");nv(null,"/")})};document.getElementById("rgB").onclick=function(){var u=document.getElementById("rgU").value,p=document.getElementById("rgP").value;api("POST","/auth/register",{username:u,password:p}).then(function(){toast("注册成功，请登录")})}}';
  h+='function pgA(){if(!CU||CU.role!=="admin"){toast("无权访问","error");nv(null,"/");return}var e=document.getElementById("app");e.innerHTML="<div class=\\"pg\\"><h2>管理面板</h2><p style=\\"color:var(--t2);margin-bottom:20px\\">论坛管理</p><div class=\\"admin-bar\\"><button id=\\"adD\\" class=\\"active\\">概览</button><button id=\\"adU\\">用户</button><button id=\\"adT\\">帖子</button></div><div id=\\"adC\\"><div class=\\"ld\\"><div class=\\"spinner\\"></div><p>加载中...</p></div></div></div>";document.getElementById("adD").onclick=function(){sgA("d")};document.getElementById("adU").onclick=function(){sgA("u")};document.getElementById("adT").onclick=function(){sgA("t")};gAD()};var at="d";function sgA(t){at=t;Array.from(document.querySelectorAll(".admin-bar button")).forEach(function(b){b.classList.remove("active")});if(at==="d"){document.getElementById("adD").classList.add("active");gAD()}else if(at==="u"){document.getElementById("adU").classList.add("active");gAU()}else if(at==="t"){document.getElementById("adT").classList.add("active");gAT()}}';
  h+='function gAD(){var e=document.getElementById("adC");e.innerHTML="<div class=\\"ld\\"><div class=\\"spinner\\"></div><p>加载中...</p></div>";api("GET","/admin/stats").then(function(s){e.innerHTML="<div class=\\"admin-stats\\"><div class=\\"card\\"><div class=\\"stat-num\\">"+s.users+"</div><div class=\\"stat-label\\">用户数</div></div><div class=\\"card\\"><div class=\\"stat-num\\">"+s.threads+"</div><div class=\\"stat-label\\">帖子数</div></div><div class=\\"card\\"><div class=\\"stat-num\\">"+s.posts+"</div><div class=\\"stat-label\\">回复数</div></div></div>"+(s.recentUsers&&s.recentUsers.length?"<div class=\\"card\\"><h4 style=\\"margin-bottom:12px\\">最近注册</h4><table class=\\"tbl\\"><thead><tr><th>ID</th><th>用户名</th><th>角色</th><th>时间</th></tr></thead><tbody>"+s.recentUsers.map(function(u){return"<tr><td>"+u.id+"</td><td>"+esc(u.username)+"</td><td>"+(u.role==="admin"?"<span class=\\"badge\\">管理员</span>":"用户")+"</td><td>"+u.created_at+"</td></tr>"}).join("")+"</tbody></table></div>":"")}).catch(function(){e.innerHTML="<p>加载失败</p>"})}';
  h+='function gAU(){var e=document.getElementById("adC");e.innerHTML="<div class=\\"ld\\"><div class=\\"spinner\\"></div><p>加载中...</p></div>";api("GET","/admin/users").then(function(us){e.innerHTML="<div class=\\"card\\"><h4 style=\\"margin-bottom:12px\\">用户管理</h4><table class=\\"tbl\\"><thead><tr><th>ID</th><th>用户名</th><th>角色</th><th>时间</th><th>操作</th></tr></thead><tbody>"+us.map(function(u){return"<tr><td>"+u.id+"</td><td>"+esc(u.username)+"</td><td>"+(u.role==="admin"?"<span class=\\"badge\\">管理员</span>":"用户")+"</td><td>"+u.created_at+"</td><td>"+(u.id!==CU.id?"<button class=\\"btn btn-sm\\" data-sr=\\""+u.id+"\\" data-srn=\\""+(u.role==="admin"?"user":"admin")+"\\">"+(u.role==="admin"?"设为用户":"设管理员")+"</button> <button class=\\"btn btn-d btn-sm\\" data-du=\\""+u.id+"\\">删除</button>":"<span style=\\"color:var(--t2)\\">当前用户</span>")+"</td></tr>"}).join("")+"</tbody></table></div>";Array.from(document.querySelectorAll("[data-sr]")).forEach(function(el){el.onclick=function(){var uid=el.getAttribute("data-sr")|0,rn=el.getAttribute("data-srn");api("POST","/admin/set-role",{user_id:uid,role:rn}).then(function(){toast("角色已更新");gAU()})}});Array.from(document.querySelectorAll("[data-du]")).forEach(function(el){el.onclick=function(){if(!confirm("确定删除？"))return;api("DELETE","/admin/users/"+el.getAttribute("data-du")).then(function(){toast("用户已删除");gAU()})}})}).catch(function(){e.innerHTML="<p>加载失败</p>"})}';
  h+='function gAT(){var e=document.getElementById("adC");e.innerHTML="<div class=\\"ld\\"><div class=\\"spinner\\"></div><p>加载中...</p></div>";api("GET","/threads?page=1").then(function(d){e.innerHTML="<div class=\\"card\\"><h4 style=\\"margin-bottom:12px\\">帖子管理</h4><table class=\\"tbl\\"><thead><tr><th>ID</th><th>标题</th><th>作者</th><th>回复</th><th>时间</th><th>操作</th></tr></thead><tbody>"+(d.threads||[]).map(function(t){return"<tr><td>"+t.id+"</td><td>"+esc(t.title).substring(0,30)+"</td><td>"+esc(t.username)+"</td><td>0</td><td>"+ago(t.created_at)+"</td><td><button class=\\"btn btn-d btn-sm\\" data-dt=\\""+t.id+"\\">删除</button></td></tr>"}).join("")+"</tbody></table></div>";Array.from(document.querySelectorAll("[data-dt]")).forEach(function(el){el.onclick=function(){if(!confirm("确定删除？"))return;api("DELETE","/threads/"+el.getAttribute("data-dt")).then(function(){toast("已删除");gAT()})}})}).catch(function(){e.innerHTML="<p>加载失败</p>"})}';
  h+='upd();rt();</script></body></html>';
  return h;
}

// ─── 主入口 ───
export default {
  async fetch(request, env, ctx) {
    try{await initDB(env)}catch(e){}
    var url=new URL(request.url),path=url.pathname;
    if(path.startsWith('/api/')){
      var p=path.replace('/api',''),m=request.method,body={};
      if(['POST','PUT','DELETE'].includes(m))try{body=await request.json()}catch(e){}
      if(p==='/auth/register'&&m==='POST')return apiReg(env,body);
      if(p==='/auth/login'&&m==='POST')return apiLog(env,body);
      if(p==='/auth/logout'&&m==='POST')return apiOut(env,request);
      if(p==='/me'&&m==='GET')return apiMe(env,request);
      if(p==='/threads'&&m==='GET')return apiThr(env,request);
      if(p.match(/^\/threads\/\d+$/)&&m==='GET')return apiThrD(env,p.split('/')[2]);
      if(p==='/threads'&&m==='POST')return apiCThr(env,request,body);
      if(p.match(/^\/threads\/\d+$/)&&m==='DELETE')return apiDTh(env,request,p.split('/')[2]);
      if(p==='/posts'&&m==='POST')return apiCPo(env,request,body);
      if(p.match(/^\/posts\/\d+$/)&&m==='DELETE')return apiDPo(env,request,p.split('/')[2]);
      if(p==='/admin/stats'&&m==='GET')return apiAS(env,request);
      if(p==='/admin/users'&&m==='GET')return apiAU(env,request);
      if(p==='/admin/set-role'&&m==='POST')return apiASR(env,request,body);
      if(p.match(/^\/admin\/users\/\d+$/)&&m==='DELETE')return apiAD(env,request,p.split('/')[3]);
      return json({error:'Not Found'},404);
    }
    try{return new Response(page(await getU(env,request)),{headers:{'Content-Type':'text/html;charset=utf-8'}})}
    catch(e){return new Response('<!DOCTYPE html><html><meta charset="UTF-8"><title>NW Forum</title><body style="display:flex;justify-content:center;align-items:center;min-height:100vh;font-family:sans-serif;color:#6b7280"><p>加载失败</p></body></html>',{headers:{'Content-Type':'text/html;charset=utf-8'}})}
  }
};